"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import my_settings

SECRET_KEY = my_settings.SECRET_KEY
DATABASES = my_settings.DATABASES



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

### (추가)아이피 추가하기
ALLOWED_HOSTS = ['127.0.0.1']



# Application definition


### (추가) 생성한 app들 추가하기
INSTALLED_APPS = [
    'oneclassapp',
    'etcapp',
    'locationapp',
    'memberapp',
    'storyapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


### (추가) HTML 관리 폴더 정의
### 'DIRS': [BASE_DIR / 'templates'], 아직 만들어진 것은 아님. 나중에 만들어줄거야
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'locationapp.context_processors.app_key',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases



### 데이터베이스가 추가될 경우
### - 사용할 APP을 아래에 추가
### - 오라클앱.router파일.DBRouter클래스이름 => router라는 파일도 만들어야해
### DBRouter라는 클래스도 만들 것임
### 위에서 정의한 것을 어디다 연결할건지 지정하는 것임
### 아까 만들었던 oracleapp에 연결할 것임
DATABASE_ROUTERS = [
   
]


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

### (수정) 한국어 설정
LANGUAGE_CODE = 'ko-kr'


### (수정) 시간대 설정
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'


### (추가) css, js, image들 관리를 위한 폴더 설정
### 추후 만들거임
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

### 세션을 처리하는 옵션
# - 브라우저가 닫히면 (프로세스 종료되면) 세션을 자동 종료하기
# - 세션에 저장된 모든 값을 비웁니다.

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
